// salinstudio-client/src/routes/Home.vue
<script setup lang="ts">
import Main from "../components/Main.vue";
import HeroCarousel from "../components/HeroCarousel.vue";
import Divider from "../components/Divider.vue";
</script>

<template>
  <Main>
    <template #content>
      <section class="hero-panel">
        <HeroCarousel />
        <div class="hero-cap-container">
          <h2 class="hero-cap">
            Mixed art with a focus on still-life, surrealism, and a splash of
            horror
          </h2>
        </div>
      </section>
      <Divider />
    </template>
  </Main>
</template>

<style scoped>
.hero-panel {
  max-width: 1200px;
  width: 100%;
  padding: 2rem 0;
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.hero-cap {
  font-size: 1.5rem;
  text-align: center;
}
</style>

// rework/src/routes/Home.tsx
import { Header } from "../components";
import "../styles/Home.css";

export const Home = () => {
  return (
    <div className="home-container">
      <Header />
      <main className="home-main">
        <div className="home-hero">
          <div className="home-hero-text-container">
            <h1 className="home-hero-heading">Welcome to my studio</h1>
            <p className="home-hero-p">
              I create art with a focus on portraits, still-life, surrealism and
              symbolism, with a splash of cartoons and horror mixed in.
            </p>
            <p className="home-hero-p">
              Follow me on Instagram or feel free to contact me on here.
            </p>
          </div>
          <a href="/gallery" className="home-hero-link">
            my art
          </a>
          <div className="home-hero-contact-container">
            <a href="" className="home-hero-contact-link">
              Contact
            </a>
            <a href="" className="home-hero-contact-link">
              Instagram
            </a>
          </div>
        </div>
        <div className="top-reel"></div>
        <div className="bot-reel"></div>
      </main>
    </div>
  );
};
